version: '2'

services:
  proxy:
    build: ./proxy
    command: bash -c "make all && ./proxy"
    volumes:
      - ./proxy:/code
      - ./logs:/var/log/erss
    expose:
      - "12345"
    ports:
      - "12345:12345"